- name: Installer et configurer NGINX sur AlmaLinux
  hosts: localhost
- name: Mettre à jour les paquets sur localhost
  hosts: localhost
  become: yes
  become_method: sudo
  vars_files:
    - secrets.yml
  tasks:
    - name: Mettre à jour les paquets
      ansible.builtin.apt:
        update_cache: yes:  become: true

    - name: Installer NGINX
      dnf:
        name: nginx
        state: present

    - name: Activer et démarrer NGINX
      systemd:
        name: nginx
        enabled: yes
        state: started

    - name: Déployer une page web personnalisée
      copy:
        dest: /usr/share/nginx/html/index.html
        content: |
          <html>
            <head><title>NGINX Test</title></head>
            <body><h1>Hello from Ansible AWX!</h1></body>
          </html>

    - name: Ouvrir le port 80 dans le firewall
      ansible.builtin.firewalld:
        service: http
        permanent: yes
        state: enabled

    - name: Recharger le firewall
      ansible.builtin.command:
        cmd: firewall-cmd --reload
