- name: Installer et configurer NGINX sur AlmaLinux
  hosts: localhost
  become: yes
  #become_method: sudo
  vars_files:
    - secrets.yml

  tasks:
    - name: Vérifier si sudo fonctionne
      ansible.builtin.command: sudo -l
      register: sudo_test
      ignore_errors: yes

    - name: Afficher le résultat de la vérification sudo
      ansible.builtin.debug:
        msg: "{{ sudo_test.stdout }}"

    - name: Mettre à jour les paquets
      ansible.builtin.dnf:
        name: "*"
        state: latest

    - name: Installer NGINX
      ansible.builtin.dnf:
        name: nginx
        state: present

    - name: Activer et démarrer NGINX
      ansible.builtin.systemd:
        name: nginx
        enabled: yes
        state: started

    - name: Déployer une page web personnalisée
      ansible.builtin.copy:
        dest: /usr/share/nginx/html/index.html
        content: |
          <html>
            <head><title>NGINX Test</title></head>
            <body><h1>Hello from Ansible AWX!</h1>
              <h2>I am Yehouda the new Devops apprenticeship! </h2>
            </body>
          </html>

    - name: Ouvrir le port 80 dans le firewall
      ansible.builtin.firewalld:
        service: http
        permanent: yes
        state: enabled

    - name: Recharger le firewall
      ansible.builtin.command:
        cmd: firewall-cmd --reload

