
- name: Envoyer des données à une API REST
  hosts: localhost
  tasks:
    - name: Créer un nouvel utilisateur
      ansible.builtin.uri:
        url: "https://jsonplaceholder.typicode.com/users"
        method: POST
        validate_certs: no
        body_format: json
        body:
          name: "Yehouda"
          email: "yehouda@example.com"
          username: "yehouda_admin"
        headers:
          Content-Type: "application/json"
        return_content: yes
      register: response

    - name: Afficher la réponse de l'API
      ansible.builtin.debug:
        msg: "{{ response.json }}"
