- name: Vérifier la connectivité des hôtes
  hosts: localhost
  tasks:
    - name: Ping localhost
      ansible.builtin.ping:
    - name: Print message
      ansible.builtin.debug:
        msg: Hello world

