
- name: Get IP information
  hosts: localhost
  tasks:
    - name: Get IP info from API
      uri:
        url: https://api.ipify.org?format=json
        method: GET
        validate_certs: no
        return_content: yes
      register: ip_info

    - name: Print IP information
      debug:
        msg: "Public IP: {{ ip_info.json.ip }}"
